FROM mediawiki:1.39.8

RUN apt-get update && \
    apt-get install --yes --no-install-recommends unzip=6.* jq=1.* curl=7.* ca-certificates=202* && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ADD ./.docker/download-extension.sh /
ADD https://raw.githubusercontent.com/wmde/wikibase-docker/262ffef7cc550381309c360e3e92507e85cd8bf6/wikibase/1.35/base/wait-for-it.sh /
ADD build/ /

RUN chmod +x /*.sh

RUN bash /download-extension.sh OAuth REL1_39;\
tar xzf OAuth.tar.gz;\
mv OAuth /var/www/html/extensions/OAuth

RUN bash /download-extension.sh Wikibase REL1_39;\
tar xzf Wikibase.tar.gz;\
mv Wikibase /var/www/html/extensions/Wikibase

# Hack so we can add a owner only oauth consumer
# https://gist.github.com/addshore/6b148942305b98251cd35203459feb7c
# TODO upstream this...
ADD https://gist.githubusercontent.com/addshore/6b148942305b98251cd35203459feb7c/raw/f0ccca15e3e820cd21c7f43c6d47d5b79c90ecb2/gistfile1.txt /var/www/html/extensions/OAuth/maintenance/addwikiAddOauth.php
