name: Tests

on:
    pull_request: null
    push:
        branches:
            - main
        tags:
            - '*'

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-main"

jobs:
    tests:
        runs-on: ubuntu-latest

        name: Tests of addwiki monorepo

        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.3
                    coverage: none

            -   uses: "ramsey/composer-install@v1"

            -   name: Run CI docker-compose if present
                run: '(test -f docker-compose-ci.yml && docker-compose --file docker-compose-ci.yml up -d) || echo No docker-compose-ci.yml, skipping step'
            -   name: Wait for docker-compose to be ready (if needed)
                run: '(test -f build/docker-compose-ci-wait.sh && build/docker-compose-ci-wait.sh) || echo No docker-compose-ci-wait.sh, not waiting'

            -
                run: composer test
