# Copied from https://github.com/symplify/symplify/blob/master/.github/workflows/daily_pull_request.yaml
name: Daily Pull Requests

on:
    workflow_dispatch:
    schedule:
        # https://crontab.guru/once-a-day
        -   cron: "0 0 * * *"

jobs:
    daily_pull_requests:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        name: "Re-Propagate Composer Dependencies to Packages"
                        run: "composer propagate"
                        branch: 'automated-re-propagate-dependencies'

                    -
                        name: "Re-Apply Rector Rules"
                        run: |
                            vendor/bin/rector process --ansi --no-progress-bar
                            composer fix
                        branch: 'automated-re-apply-rector'

        name: ${{ matrix.actions.name }}

        runs-on: ubuntu-latest

        steps:
            -
                uses: actions/checkout@v2

            # see https://github.com/shivammathur/setup-php
            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: none

            -   uses: "ramsey/composer-install@v1"

            -   run: ${{ matrix.actions.run }}

            # see https://github.com/peter-evans/create-pull-request
            -
                name: Create pull-request
                uses: peter-evans/create-pull-request@v3
                with:
                    author: "addwiki-ci <ci@addwiki.github.io>"
                    token: ${{ secrets.ACCESS_TOKEN }}
                    commit-message: "[automated] ${{ matrix.actions.name }}"
                    base: 'main'
                    branch: ${{ matrix.actions.branch }}
                    title: '[automated] ${{ matrix.actions.name }}'
                    delete-branch: true
