name: Split Monorepo Dev-Main
# Mainly copied from https://github.com/symplify/symplify/blob/master/.github/workflows/split_monorepo.yaml
# per the advice at https://github.com/symplify/monorepo-builder

on:
    push:
        branches:
            - main

jobs:

    split_monorepo:
        name: Split tagged ${{ matrix.package }}
        concurrency: split_${{ matrix.package }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                package:
                    - addwiki-cli
                    - mediawiki-api
                    - mediawiki-api-base
                    - mediawiki-commands
                    - mediawiki-datamodel
                    - mediawiki-flow-api
                    - mediawiki-sitematrix-api
                    - wikibase-api
                    - wikibase-commands
                    - wikibase-datamodel
                    - wikibase-query
                    - wikimedia
                    - wikimedia-commands

        steps:
            -
                uses: actions/checkout@v3

            -
                # Uses an action in the root directory
                name: Monorepo Split of ${{ matrix.package }}
                uses: symplify/github-action-monorepo-split@v2.3.0
                env:
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                with:
                    package_directory: 'packages/${{ matrix.package }}'
                    repository_organization: 'addwiki'
                    repository_name: '${{ matrix.package }}'
                    branch: "main"
                    user_name: "addwiki-ci"
                    user_email: "ci@addwiki.github.io"
